#!/bin/bash

# Flags parsing
while test $# -gt 0; do
    case "$1" in
    -v|--verbose)
        pappa="sas"
        break
    ;;
    *)
        break
    ;;
    esac
done

pidof dunst && killall dunst  
dunst &

if [ -n "$pappa" ] 
then 
    pidof dunst && notify-send "Dunst" "dunst has been reloaded"
fi

